//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Korisnik
    {
        public int KorisnikID { get; set; }
        [DisplayName("Name")]
        [Required(ErrorMessage ="Morate uneti ime")]
        public string Ime { get; set; }
        [DisplayName("Surname")]
        public string Prezime { get; set; }
        [Required(ErrorMessage ="Unesite email")]
        [DataType(DataType.EmailAddress,ErrorMessage ="Unesite pravilan format")]
        public string Gmail { get; set; }
        public Nullable<int> Racun { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage ="Unesi password")]
        public string Password { get; set; }
        
    }
}
