//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProdavnicaEntities : DbContext
    {
        public ProdavnicaEntities()
            : base("name=ProdavnicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<MagacinProizvodi> MagacinProizvodis { get; set; }
        public virtual DbSet<ProdavnicaProizvodi> ProdavnicaProizvodis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
